### ISSUE TITLE
typedef struct

### ISSUE THREAD

**Issue by unrzn0** [joshpeterson/layout#1]
Hi, interesting project. Little bit tricky to build on macOS, but works and provides interesting insights ;)

One issue I found though was that the parser seems to have issues with code like this:

```
struct Type;

typedef struct EventInfo
{
  Type* declaringType;
} EventInfo;
```
Then I get in the auto-generated code sections that still contain the 'struct' keyword, which breaks the build. One other minor thing: newer gcc/clang complain when argc/argv are commented out.

**Comment by joshpeterson** [comment]
I did have the macOS build working a while ago, but I abandoned it when filesystem support in the C++ standard library broke. Since I created the https://structlayout.herokuapp.com/ website, I didn't think too much about macOS. I'm pretty sure filesystem support was merged in libc++ now though, so maybe macOS is worth visiting again.

Did you get the tests to build and run on macOS? If so please submit a pull request!

I'll have a look at the code generation for this case - it should be possible to correct. Thanks!

**Comment by joshpeterson** [comment]
I've just got around to trying this finally today. I don't see any problems with this code snippet. You can try it yourself here:

https://structlayout.herokuapp.com/?code=struct%20Type%3B%0A%0Atypedef%20struct%20EventInfo%0A%7B%0A%20%20Type*%20declaringType%3B%0A%7D%20EventInfo%3B;args=;type=cpp

It looks like the code it generates compiles and runs properly:

https://wandbox.org/permlink/Lp7YaOjlLuPGdcpv

Can you describe the problem with this code more clearly?
